name: Build and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Restore dependencies
        run: dotnet restore NmeaTransport.sln

      - name: Build
        run: dotnet build NmeaTransport.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test NmeaTransport.sln --no-build --configuration Release --verbosity normal

      - name: Verify formatting
        run: dotnet format NmeaTransport.sln --verify-no-changes
